apiVersion: v1
kind: Pod
metadata:
  name: s3time
  namespace: default
spec:
  containers:
    - name: s3time
      image: 223615444511.dkr.ecr.eu-west-1.amazonaws.com/s3time:latest
      imagePullPolicy: Always
      env:
      - name: S3_BUCKET
        value: "ollytimexporter"
  restartPolicy: Never